### ISSUE TITLE
Ankiweb share link is dead

### ISSUE THREAD

**Issue by Cdingo** [munro/anki-dota2#1]
Hello,

The link to the shared album, https://ankiweb.net/shared/info/1019972773, is dead. Can you please re-upload and/or update the link?

**Comment by Cdingo** [comment]
I've recreated the deck using the cedota2 fork and uploaded at https://ankiweb.net/shared/info/494272399

**Comment by munro** [comment]
Ahhh yayyyyy, I was trying to regenerate it but something has broken ;_;
