### ISSUE TITLE
"Anki shared item is no longer available" error

### ISSUE THREAD

**Issue by cognivore** [munro/anki-dota2#2]
How can I help you to restore it?

**Comment by munro** [comment]
https://github.com/munro/anki-dota2/blob/main/Dota%202.apkg

I still had the media files download, just I was able to just repackage it & upload to github!  I think Ankiweb will keep deleting decks after awhile.  This deck is from Dota 2 back in 2018, so it's probably really outdated—I gave you access if you wanted to try and update it—basically everything is really outdated 🥴

**Comment by cognivore** [comment]
Alright, I'll do my best to learn Anki, but probably around the next TI.

The project, in theory, is really helpful. Such a shame it didn't get traction in the community.
